// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// backward_forward
Rcpp::List backward_forward(const arma::mat& fit, const arma::cube& Gamma, const arma::vec& Pi_in, const int K, const int M);
RcppExport SEXP _hsmm_backward_forward(SEXP fitSEXP, SEXP GammaSEXP, SEXP Pi_inSEXP, SEXP KSEXP, SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type fit(fitSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type Gamma(GammaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Pi_in(Pi_inSEXP);
    Rcpp::traits::input_parameter< const int >::type K(KSEXP);
    Rcpp::traits::input_parameter< const int >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(backward_forward(fit, Gamma, Pi_in, K, M));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_hsmm_backward_forward", (DL_FUNC) &_hsmm_backward_forward, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_hsmm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
