# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

backward_forward <- function(fit, Gamma, Pi_in, K, M) {
    .Call(`_hsmm_backward_forward`, fit, Gamma, Pi_in, K, M)
}

